package com.mycompany.sistema_veterinario.front;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.mycompany.sistema_veterinario.back.service.Productos_Manager;
import com.mycompany.sistema_veterinario.back.model.Productos;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author dikeg
 */
public class Productos_View extends javax.swing.JFrame {

    /**
     * Creates new form Productos_View
     */
    public Productos_View() {
   
        initComponents();
    cargarProductosEnTabla();
}

   
private String generarId() {
    return String.valueOf(System.currentTimeMillis());
}

 public void cargarProductosEnTabla() {

    DefaultTableModel modelo = (DefaultTableModel) TablaProductos.getModel();
    modelo.setRowCount(0); // limpia la tabla

    try {
        ArrayList<Productos> lista = Productos_Manager.listarProductos();

        for (Productos p : lista) {
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getStock(),
                p.getPrecio(),
                p.getActivo()
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "No se pudieron cargar los productos: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btAgregar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CATEGORIA", "STOCK", "PRECIO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setResizable(false);
            TablaProductos.getColumnModel().getColumn(1).setResizable(false);
            TablaProductos.getColumnModel().getColumn(2).setResizable(false);
            TablaProductos.getColumnModel().getColumn(3).setResizable(false);
            TablaProductos.getColumnModel().getColumn(4).setResizable(false);
            TablaProductos.getColumnModel().getColumn(5).setResizable(false);
        }

        btAgregar.setText("Agregar productos");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        jButton1.setText("Quitar productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar productos");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_editar)
                .addGap(18, 18, 18)
                .addComponent(btAgregar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btRegresar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
      JTextField txtId = new JTextField();
        JTextField txtNombre = new JTextField();
    JTextField txtCategoria = new JTextField();
    JTextField txtStock = new JTextField();
    JTextField txtPrecio = new JTextField();

    Object[] formulario = {
         "Id:", txtId,
        "Nombre:", txtNombre,
        "Categoría:", txtCategoria,
        "Stock:", txtStock,
        "Precio:", txtPrecio
    };

    int opcion = JOptionPane.showConfirmDialog(
        this,
        formulario,
        "Agregar producto",
        JOptionPane.OK_CANCEL_OPTION
    );

    if (opcion == JOptionPane.OK_OPTION) {
        try {
            Productos p = new Productos(
                txtId.getText(),
                txtNombre.getText(),
                txtCategoria.getText(),
                Integer.parseInt(txtStock.getText()),
                Double.parseDouble(txtPrecio.getText()),
                true
            );

            if (!Productos_Manager.guardarProducto(p)) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo guardar el producto");
                return;
            }

            cargarProductosEnTabla();

            JOptionPane.showMessageDialog(this, "Producto agregado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos inválidos");
        }
    }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        try {
            Inicio_Admin inicio = new Inicio_Admin();
           inicio.setVisible(true);
           this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int fila = TablaProductos.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto");
        return;
    }

    String id = TablaProductos.getValueAt(fila, 0).toString();

    int confirmar = JOptionPane.showConfirmDialog(
        this,
        "¿Seguro que deseas eliminar este producto?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmar == JOptionPane.YES_OPTION) {
        try {
            if (Productos_Manager.eliminarProducto(id)) {
                cargarProductosEnTabla();
                JOptionPane.showMessageDialog(this, "Producto eliminado");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el producto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el producto: " + e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
int fila = TablaProductos.getSelectedRow();
if (fila ==-1){
JOptionPane.showMessageDialog(null, "Selecciona un producto");
return;
}
String codigo = TablaProductos.getValueAt(fila, 0).toString();
String nombre = TablaProductos.getValueAt(fila, 1).toString();
String categoria = TablaProductos.getValueAt(fila,2 ).toString();
JTextField txtPrecio = new JTextField(
        TablaProductos.getValueAt(fila, 4).toString());

JTextField txtStock = new JTextField(
        TablaProductos.getValueAt(fila, 3).toString());

JCheckBox chkActivo = new JCheckBox(
        "Producto activo",
        Boolean.parseBoolean(
                TablaProductos.getValueAt(fila, 5).toString()));
Object [] formulario = {
      "Código: " + codigo,
    "Nombre: " + nombre,
    "Categoría: " + categoria,
    "Nuevo stock:", txtStock,
    "Nuevo precio:", txtPrecio,
    chkActivo
};

int confirmar = JOptionPane.showConfirmDialog(this,formulario,"Editar Prodcuto",
        JOptionPane.OK_CANCEL_OPTION);
if(confirmar == JOptionPane.OK_OPTION){
    try{
       int stock = Integer.parseInt(txtStock.getText());
       double precio = Double.parseDouble(txtPrecio.getText());
       boolean activo = chkActivo.isSelected();
       if(stock < 0 || precio < 0){
           JOptionPane.showMessageDialog(this, "El stock y el precio no deben ser menores a 0");
           return;
       }
       boolean actualizado =
       Productos_Manager.editarProducto(codigo, precio, stock, activo);
       if(actualizado){
           cargarProductosEnTabla();
           JOptionPane.showMessageDialog(this,
                    "Producto actualizado correctamente");
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar el producto");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Stock y precio deben ser valores numéricos");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage());
    }
}
       

    }//GEN-LAST:event_bt_editarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
