/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_veterinario;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.time.LocalDate;



/**
 *
 * @author ADMINISTRATOR
 */
public class Agendar_citas extends javax.swing.JFrame {
private int idUsuario;
    /**
     * Creates new form Registro
     * 
     */

 private void llenarcombofecha(){
        jcdia.removeAllItems();
        jcmes.removeAllItems();
        jcanios.removeAllItems();
        
        for (int i = 1; i <= 31; i++){
            jcdia.addItem(String.valueOf(i));  
        }
        
        for (int i = 1; i <= 12; i++){
            jcmes.addItem(String.valueOf(i));
        }
        
        for (int i = 2026; i <= 2036; i++){
          jcanios.addItem(String.valueOf(i));
        }        
    }
    public Agendar_citas(int idUsuario) {
     
        initComponents();
        llenarcombofecha();
        this.idUsuario=idUsuario;
        DefaultTableModel modelo = new DefaultTableModel(
        new Object[][]{},
        new String []{"Cliente", "Mascota", "Celular","Fecha"}
       ){
           @Override
           public boolean isCellEditable(int row , int column){
               return false;
           }
       };
    tblconsultas.setModel(modelo);
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblconsultas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbcliente = new javax.swing.JLabel();
        txcliente = new javax.swing.JTextField();
        lbmtipo = new javax.swing.JLabel();
        txtipo = new javax.swing.JTextField();
        lbcelular = new javax.swing.JLabel();
        txcelular = new javax.swing.JTextField();
        lbfecha = new javax.swing.JLabel();
        btregistrar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        jcdia = new javax.swing.JComboBox<>();
        jcmes = new javax.swing.JComboBox<>();
        jcanios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblconsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CLIENTE", "MASCOTA", "CELULAR", "FECHA"
            }
        ));
        tblconsultas.setToolTipText("");
        jScrollPane2.setViewportView(tblconsultas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  REGISTRO DE CONSULTAS");

        lbcliente.setBackground(new java.awt.Color(255, 255, 255));
        lbcliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcliente.setForeground(new java.awt.Color(255, 255, 255));
        lbcliente.setText("Cliente");

        txcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txclienteActionPerformed(evt);
            }
        });

        lbmtipo.setBackground(new java.awt.Color(255, 255, 255));
        lbmtipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbmtipo.setForeground(new java.awt.Color(255, 255, 255));
        lbmtipo.setText("Tipo de mascota");

        lbcelular.setBackground(new java.awt.Color(255, 255, 255));
        lbcelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcelular.setForeground(new java.awt.Color(255, 255, 255));
        lbcelular.setText("Numero de celular");

        lbfecha.setBackground(new java.awt.Color(255, 255, 255));
        lbfecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbfecha.setText("Fecha de la consulta");

        btregistrar.setText("REGISTRAR");
        btregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarActionPerformed(evt);
            }
        });

        bteliminar.setText("ELIMINAR");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btRegresar.setText("REGRESAR");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        jcdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", " " }));
        jcdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdiaActionPerformed(evt);
            }
        });

        jcmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));

        jcanios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", " " }));
        jcanios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcaniosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btregistrar))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbfecha)
                                .addGap(18, 18, 18)
                                .addComponent(jcdia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcanios, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbcelular)
                                    .addComponent(lbcliente)
                                    .addComponent(lbmtipo))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtipo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txcliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmtipo)
                    .addComponent(txtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcelular)
                    .addComponent(txcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfecha)
                    .addComponent(jcdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bteliminar)
                .addGap(24, 24, 24)
                .addComponent(btRegresar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        Inicio_Admin inicio = new Inicio_Admin();
        inicio.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) tblconsultas.getModel();
        int filaSeleccionada = tblconsultas.getSelectedRow();

        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA FILA");
            return;
        }
        int confirmar = JOptionPane.showConfirmDialog(this, "ELIMINAR");
        // TODO add your handling code here:
        if(confirmar == JOptionPane.YES_OPTION){
            modelo.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "ELIMINADO CORRECTAMENTE");
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblconsultas.getModel();
        String Cliente = txcliente.getText();
        String Mascota = txtipo.getText();
        String Celular = txcelular.getText();
        String Fecha = jcdia.getSelectedItem() + "/" +jcmes.getSelectedItem()+"/" +jcanios.getSelectedItem();
        
        if(jcdia.getSelectedItem() == null || jcmes.getSelectedItem() == null || jcanios.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Selecciona la fecha completa");
            return;
        }

        if(txcliente.getText().isEmpty() || txtipo.getText().isEmpty() || txcelular.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "TODOS LOS CAMPOS SON OBLIGATORIOS");
                    return;

        }
        if (!txcelular.getText().matches("\\d{10}")){
            JOptionPane.showMessageDialog(this, "EL NUMERO DE CELULAR DEBE TENER 10 DIGITOS");
            return;
        }

        //Se agrega en la tabla
        modelo.addRow(new Object[]{
            Cliente, Mascota, Celular
        });
        try {
            FileWriter fw = new FileWriter("consultas.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            pw.println(Cliente +"," +Mascota+","+Celular+","+Fecha);

            pw.close();
        }catch (IOException e){
            System.out.println("ERROR EN GUARDAR ARCHIVO");
        }

        txcliente.setText("");
        txtipo.setText("");
        txcelular.setText("");
    

        // TODO add your handling code here:
    }//GEN-LAST:event_btregistrarActionPerformed

    private void txclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txclienteActionPerformed

    private void jcdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcdiaActionPerformed

    private void jcaniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcaniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcaniosActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcanios;
    private javax.swing.JComboBox<String> jcdia;
    private javax.swing.JComboBox<String> jcmes;
    private javax.swing.JLabel lbcelular;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbmtipo;
    private javax.swing.JTable tblconsultas;
    private javax.swing.JTextField txcelular;
    private javax.swing.JTextField txcliente;
    private javax.swing.JTextField txtipo;
    // End of variables declaration//GEN-END:variables
}
