/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_veterinario;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dikeg
 */
public class Tienda_View extends javax.swing.JFrame {
private Carrito_Manager carrito;
private Tienda_View tienda;
    /**
     * Creates new form Tienda_View
     * @param carrito
     */
    public Tienda_View(Carrito_Manager carrito, Tienda_View tienda) {
    initComponents();
    this.tienda=tienda;
    this.carrito = carrito;
    cargarProductosEnTabla();


    }
public void cargarProductosEnTabla() {

    DefaultTableModel modelo = (DefaultTableModel) TablaTienda.getModel();
    modelo.setRowCount(0); // limpiar tabla

    ArrayList<Productos> lista = Productos_Manager.listarProductos();

    for (Productos p : lista) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNombre(),
            p.getCategoria(),
            p.getPrecio(),
            p.getStock()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTienda = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        btComprar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        btCarrito = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaTienda);

        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btComprar.setText("COMPRAR");
        btComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarActionPerformed(evt);
            }
        });

        btRegresar.setText("REGRESAR");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btCarrito.setText("VER CARRITO");
        btCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarritoActionPerformed(evt);
            }
        });

        jButton1.setText("AGREGAR A CARRITO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btRegresar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCarrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btComprar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btComprar)
                    .addComponent(btCarrito))
                .addGap(23, 23, 23)
                .addComponent(btRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        String nombreBuscar = JOptionPane.showInputDialog(this, "Ingrese el nombre del producto:");
    
    if (nombreBuscar != null && !nombreBuscar.isEmpty()) {
        DefaultTableModel modelo = (DefaultTableModel) TablaTienda.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla

        ArrayList<Productos> lista = Productos_Manager.listarProductos();
        boolean encontrado = false;

        for (Productos p : lista) {
            // Buscamos coincidencias por nombre (ignora mayúsculas/minúsculas)
            if (p.getNombre().toLowerCase().contains(nombreBuscar.toLowerCase())) {
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getNombre(),
                    p.getCategoria(),
                    p.getPrecio(),
                    p.getStock()
                });
                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron productos con ese nombre.");
            cargarProductosEnTabla(); // Recargamos todo si no hay resultados
        }
    } else {
        cargarProductosEnTabla(); // Si cancela o deja vacío, muestra todo
    }
    }//GEN-LAST:event_btBuscarActionPerformed


    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        try {
            Inicio_User inicio = new Inicio_User();
            inicio.setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarActionPerformed
private void generarFacturaTXT(String producto, int cant, double precio, double sub, double iva, double total) {
    try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.FileWriter("factura_" + System.currentTimeMillis() + ".txt"))) {
        writer.println("========================================");
        writer.println("           VeterinariaDesk             ");
        writer.println("========================================");
        writer.println("Fecha: " + new java.util.Date());
        writer.println("----------------------------------------");
        writer.println("Producto: " + producto);
        writer.println("Cantidad: " + cant);
        writer.println("Precio Unit.: $" + precio);
        writer.println("----------------------------------------");
        writer.println("Subtotal: $" + String.format("%.2f", sub));
        writer.println("IVA (15%): $" + String.format("%.2f", iva));
        writer.println("TOTAL A PAGAR: $" + String.format("%.2f", total));
        writer.println("----------------------------------------");
        writer.println("   ¡Gracias por confiar en nosotros!    ");
        writer.println("========================================");
    } catch (java.io.IOException e) {
        System.out.println("Error al crear la factura: " + e.getMessage());
    }
}
    private void btComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarActionPerformed
        // TODO add your handling code here:
      int fila = TablaTienda.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
    }

    String id = TablaTienda.getValueAt(fila, 0).toString();
    String nombre = TablaTienda.getValueAt(fila, 1).toString();
    double precioUnitario = Double.parseDouble(TablaTienda.getValueAt(fila, 3).toString());
    int stockDisponible = Integer.parseInt(TablaTienda.getValueAt(fila, 4).toString());

    String input = JOptionPane.showInputDialog(this, "¿Cantidad de " + nombre + " a comprar?");
    if (input == null || input.isEmpty()) return;

    try {
        int cantidad = Integer.parseInt(input);
        if (cantidad <= 0 || cantidad > stockDisponible) {
            JOptionPane.showMessageDialog(this, "Cantidad no válida o stock insuficiente");
            return;
        }

        // Cálculos financieros
        double subtotal = precioUnitario * cantidad;
        double iva = subtotal * 0.15; // Ajusta al 15% o según tu país
        double total = subtotal + iva;

        // 1. Procesar la compra en el sistema
        for(int i = 0; i < cantidad; i++) {
            Productos_Manager.comprarProducto(id);
        }

        // 2. GENERAR FACTURA TXT
        generarFacturaTXT(nombre, cantidad, precioUnitario, subtotal, iva, total);

        JOptionPane.showMessageDialog(this, "¡Compra exitosa! Factura generada como 'factura_" + id + ".txt'");
        cargarProductosEnTabla();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar la compra");
    }

    }//GEN-LAST:event_btComprarActionPerformed

    private void btCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarritoActionPerformed
        // TODO add your handling code here:
         Carrito_View vistaCarrito = new Carrito_View(carrito, this);
    vistaCarrito.setVisible(true);
    this.setVisible(false);
        
    }//GEN-LAST:event_btCarritoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int fila = TablaTienda.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
    }

    // 1. Obtener datos de la fila seleccionada
    String id = TablaTienda.getValueAt(fila, 0).toString();
    String nombre = TablaTienda.getValueAt(fila, 1).toString();
    int stockDisponible = Integer.parseInt(TablaTienda.getValueAt(fila, 4).toString());

    // 2. Pedir cantidad para el carrito
    String input = JOptionPane.showInputDialog(this, 
        "Producto: " + nombre + "\nStock disponible: " + stockDisponible + "\n¿Cuántos desea agregar?");
    
    if (input == null || input.isEmpty()) return;

    try {
        int cantidadAAgregar = Integer.parseInt(input);

        // 3. Validaciones rápidas
        if (cantidadAAgregar <= 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos 1 unidad");
            return;
        }

        if (cantidadAAgregar > stockDisponible) {
            JOptionPane.showMessageDialog(this, "No hay suficiente stock. Solo quedan " + stockDisponible);
            return;
        }

        // 4. Buscar el producto y agregarlo la cantidad de veces necesaria
        for (Productos p : Productos_Manager.listarProductos()) {
            if (p.getId().equals(id)) {
                // Agregamos el producto al carrito según la cantidad pedida
                for (int i = 0; i < cantidadAAgregar; i++) {
                    carrito.agregarProducto(p);
                }
                JOptionPane.showMessageDialog(this, cantidadAAgregar + " unidades de '" + nombre + "' agregadas al carrito");
                return;
            }
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Ingrese un número entero válido");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTienda;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCarrito;
    private javax.swing.JButton btComprar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
